### PR TITLE
Fix normalization of sensitivity measure

### PR DESCRIPTION
**Pull request by AlexVanMeegen**
Addresses #50. Use `scipy.linalg.eig` to get left eigenvectors instead of `np.linalg.eig` and `np.linalg.inv` which implicitly assumes that the eigenvalues are nondegenerate.

This does not affect the `sensitivity_measure.py` example because the eigenvalues are not degenerate.

### CODE REVIEW

**Comment by AlexVanMeegen** [comment]
Just to be clear: I don't think this is a relevant problem. It is safer but I guess the effective connectivity is always normal. The main motivation is to match the code with the corresponding equation (7) in [the paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005132#pcbi.1005132.e015).

**Comment by moritzlayer** [comment]
Looks good to me. As soon as the tests are merged and provided all tests still pass (which I strongly suppose) this PR can be merged.

**Comment by moritzlayer** [comment]
Hey @AlexVanMeegen, I would like to add the updated fixture data, but you first need to allow the maintainers to edit the PR.

**Comment by AlexVanMeegen** [comment]
Weird, the box is ticked: 
image
Is there anything else I need to do?

**Comment by moritzlayer** [comment]
Sorry it was a mistake on my side. I was working in the wrong local repository...

**Comment by AlexVanMeegen** [comment]
No worries. Thanks for merging. And big hat tip for the integration test PR, impressive work!

**Pull request merged**
